name       : xfconf
version    : 4.18.0
release    : 5
source     :
    - https://archive.xfce.org/xfce/4.18/src/xfconf-4.18.0.tar.bz2 : 2e8c50160bf800a807aea094fc9dad81f9f361f42db56607508ed5b4855d2906
homepage   : https://docs.xfce.org/xfce/xfconf/start
license    : GPL-2.0-or-later
component  : system.utils
summary    : Xfce configuration storage system
description: |
    Xfconf is a hierarchical (tree-like) configuration system where the immediate child nodes of the root are called “channels”. All settings beneath the channel nodes are called “properties.”
builddeps  :
    - pkgconfig(libxfce4util-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
